### PR TITLE
Avoid file name being too long for ecryptfs users.

### PR DESCRIPTION
**Pull request by JulienPalard**
In https://github.com/pyvideo/data/pull/1075 I didn't investigated, just fixing the thing, daydreaming it was enough...

Today I `git pull` and bim, file too long again, so this time I investigated, found the real cause, and added a test!

It's not the full path that's being too long, that's just the file names, which are limited to around 140 chars on eCryptfs due to eCryptfs having to write some data before the filename, and the actual filename is typically limited to 255 bytes by the underlying filesystem.

Looks like I'm alone in this repo using eCryptfs, so in one hand I think « 140 bytes ought to be enough for anybody », on the other hand I'll understand if this PR gets rejected, and will probably switch to full disk encryption anyway, no worries.

### CODE REVIEW

**Comment by logston** [comment]
This is great! Thanks Julien! Looks like the tests do not run on Python 3.5. Can you update that?

**Review by logston — APPROVED** [review]

**Comment by JulienPalard** [comment]
Python 3.5 is EOL since octobre 2020, can I try to bump the CI to the current stable instead of trying to keep 3.5 compatibility, or is there a good reason I missed to keep 3.5 around here?

**Comment by JulienPalard** [comment]
@logston rebased so the tests now pass using Python 3.9.

**Comment by logston** [comment]
Thanks again!

**Pull request merged**
