### PR TITLE
Add PyCon Israel 2017

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by Daniel-at-github** [comment]
Could you enable "Allow edits from maintainers"? (Right column, may be here or below ===>)

Usually it's more complicated to tell it than to modify it. Example:
In "A primer to write a conversational chatbot - Francesco Vollero - Pycon Israel 2017" speaker is missing and the title should be "A primer to write a conversational chatbot" because the rest of the information should be in other fields. ...

**Comment by Daniel-at-github** [comment]
Why reviewers and asignees? The answer in:
https://stackoverflow.com/questions/41087206/on-github-whats-the-difference-between-reviewer-and-assignee 
I will review it and (if @rollandf enable "Allow edits from maintainers") the two of us could enhance the pull request.

**Comment by rollandf** [comment]
I fixed some issues.
 "Allow edits from maintainers" is enabled.
Thanks !!

**Comment by Daniel-at-github** [comment]
This talks slides links are broken:
* Exploring and Analyzing Open Satellite Imagery data
* Jenkins as a Python execution platform
* Unit tests and TDD does NOT have to be boring

No lightning talks?

**Comment by rollandf** [comment]
Please delete the links. I am not sure they will be fixed. I will ask the person in charge of the Pycon IL site.
No Lightning talks.
I am OK with merging, I will fix the links later if they will be fixed.
Thanks for the help.
👍

**Pull request merged**
