### PR TITLE
Added project description, speaker, and tags to PyData Austin 2019.  …

### PR DESCRIPTION
**Pull request by Grimmaldi**
…Updated title, removing conference and speaker name.

### CODE REVIEW

**Comment by Grimmaldi** [comment]
I've finished tagging all of the videos for PyData Austin 2019.  Can someone please merge or let me know if anything needs to be corrected?

**Comment by di** [comment]
Thanks!

**Comment by Grimmaldi** [comment]
You're welcome!   Just out of curiosity, when will these changes be visible on the Pyvideo site?

**Comment by di** [comment]
@Grimmaldi It gets updated when the changes are pulled into https://github.com/pyvideo/pyvideo

**Comment by Daniel-at-github** [comment]
As minor issue: For consistence tags should be in lowercase. See https://github.com/pyvideo/data/blob/master/CONTRIBUTING.rst#tags

**Pull request merged**
