### PR TITLE
PyCon AU 2020

### LINKED ISSUE #1068: PyCon AU 2020
```
- title: PyCon AU 2020
  dir: pycon-au-2020
  issue: 1068
  youtube_list:
    - https://www.youtube.com/playlist?list=PLs4CJRBY5F1IEFq-wumrBDRCu2EqkpY-R
  related_urls:
  - label: Conference schedule
    url: https://2020.pycon.org.au/program/
  language: eng
  dates:
    begin: 2020-09-04
    end: 2020-09-06
    default: 2020-09-05
  tags:
```

### PR DESCRIPTION
**Pull request by glasnt**
I had some issues with the scraper, as it didn't get any license information from ydl. I ended up manually changing my copy of the scraper to enter the custom license this event uses, hope that's alright. 

Fixes #1068

Event config:
~~~yaml
events:
- title: PyCon AU 2020
  dir: pycon-au-2020
  issue: 1068
  youtube_list:
   - https://www.youtube.com/playlist?list=PLs4CJRBY5F1IEFq-wumrBDRCu2EqkpY-R
  related_urls:
  - label: Conference schedule
    url: https://2020.pycon.org.au/program/
  language: eng
  dates:
    begin: 2020-09-04
    end: 2020-09-06
    default: 2020-09-05
  tags:

~~~

### CODE REVIEW

**Comment by redapple** [comment]
Thank you @glasnt !
Can I ask you to remove the speakers and "PyConline AU 2020" from the titles?

**Comment by glasnt** [comment]
Oop, yup, thank you!

**Comment by glasnt** [comment]
I'll do the same for the other PR

**Review by toshee23 — COMMENTED** [review]
----

**Comment by logston** [comment]
Hi @toshee23, I'm not sure if that is language that you and @glasnt have previously agreed upon as permissible in your relationship. Regardless, please refrain from such language here at PyVideo as it is against our code of conduct. 

https://github.com/pyvideo/pyvideo/wiki/Development-Philosophy#the-people

**Comment by glasnt** [comment]
I'm sorry @logston I have no idea who this person is.

**Comment by logston** [comment]
I apologize @glasnt, you have nothing to be sorry for. Thanks for letting me know.

**Pull request closed without merging**
