### PR TITLE
Fix broken DjangoCon Europe 2016 links. Closes #584.

### LINKED ISSUE #584: DjangoCon Europe 2016 links are broken
Something seems to be wrong with DjangoCon Europe 2016. Search results for videos from the event don't contain a video snapshot and link to a 404 error page (for an example, search `reactjs`). The event page contains placeholder snapshot images: https://pyvideo.org/events/djangocon-europe-2016.html And the talk pages linked from the events page don't contain a video.

### PR DESCRIPTION
**Pull request by zerok**

### CODE REVIEW

**Comment by redapple** [comment]
Hi @zerok , the video links do not work for me.
Thumbnail links do work though.
Are the vimeo videos private or something?

**Comment by zerok** [comment]
Sadly one video is password protected, the others worked yesterday 😔 will recheck in the next couple of days

**Comment by redapple** [comment]
@zerok , I merged the PR,
and while the videos loaded in the player when I tested locally,
it doesn't work on pyvideo.org (e.g. https://pyvideo.org/djangocon-europe-2016/using-django-with-service-workers.html)

**Comment by zerok** [comment]
Damn, I will mail someone from Elastic about it. Perhaps they can fix the permissions 😄

**Comment by redapple** [comment]
@zerok , actually I pinged them on Twitter, and sent them the list of URLs
(cf. https://twitter.com/skywy/status/1059775380381417472)
have not heard from them yet but they know :)

**Pull request merged**
