### PR TITLE
Add Ram Rachum's talk (Live-coding a music synthesizer)

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by di** [comment]
Hi, thanks for the PR. Would you be able to add the rest of the EuroPython 2020 videos as well?

**Comment by cool-RR** [comment]
I did my own manually. Doing the entire stack of EuroPython 2020 talks would require writing a script or something. I don't know if someone usually does this, but I don't want to volunteer for that, sorry.

**Comment by di** [comment]
See https://github.com/pyvideo/data/blob/master/CONTRIBUTING.rst and https://github.com/pyvideo/data/tree/master/tools

**Comment by cool-RR** [comment]
Can you be more specific? I see there's a section about making JSON pretty-printed and I can do that, but first I want to understand what's missing to make this PR mergeable.

**Comment by logston** [comment]
We like to import a whole conference worth of videos at a time. This way, when the site says "New Conference...", all the videos are there. You're talk will certainly be included but would you mind performing the scrape to gather the rest of the talk material? This section has links to the tools that can help you do that: https://github.com/pyvideo/data/blob/master/CONTRIBUTING.rst#creating-data-from-youtube-channel

**Comment by gilgamezh** [comment]
Hello! all Europython videos are in this PR https://github.com/pyvideo/data/pull/1045

**Pull request closed without merging**
