### PR TITLE
Talks from PyCon.De 2016 in Munich

### PR DESCRIPTION
**Pull request by ivan-bilan**
Added JSON Files with the talks from PyCon.De 2016 in Munich.  All authors have agreed to the distribution of the recordings.

### CODE REVIEW

**Comment by Daniel-at-github** [comment]
Hi, I have tried your branch. 
To fix it you have to reserialize it from the root directory of the repository, like this:
~~~ bash
python tools/reserialize.py --all .
# and pass the tests
make test
~~~
I have https://github.com/pyvideo/pyvideo in `~/git/pyvideo` and https://github.com/pyvideo/data in `~/git/pyvideo/data` in this way I can preview how the changes will look with:
~~~ bash
cd ~/git/pyvideo
make html VERBOSE=1 && make serve # Will serve it in http://localhost:8000
~~~

**Comment by Daniel-at-github** [comment]
Seems that 4 files still need to reserialize. 
>	pycon-de-2016/videos/powered-by-python-summarizing-hotel-reviews-for-10000-hotels-and-100-million-travelers.json
	pycon-de-2016/videos/processing-music-on-the-fly-with-python.json
	pycon-de-2016/videos/profiling-the-unprofilable.json
	pycon-de-2016/videos/when-we-were-young-and-in-love.json

reserialize and `make test` before the pull request, it's the most useful to avoid travis annoyances.

**Comment by ivan-bilan** [comment]
When  I run make test, I get this error:

ImportError: No module named 'jsonschema'
Makefile:29: recipe for target 'test-schemas' failed
make: *** [test-schemas] Error 1

And jsonschema is already installed! So strange. I have serialized all the files now, should work.

**Comment by logston** [comment]
This is great! Thanks for your work @ivan-bilan and for your help @Daniel-at-github.

**Comment by ivan-bilan** [comment]
Thanks! How long does it usually take for the talks to appear on the website?

**Comment by logston** [comment]
Couple days. @lgh2 Manages deploys and she preps them quite regularly.

**Pull request merged**
