### PR TITLE
Add PyCon AU 2018

### PR DESCRIPTION
**Pull request by glasnt**

### CODE REVIEW

**Comment by glasnt** [comment]
Thanks for the edits here!

re: cc757b9 the `make test` was complaining about a leading asterisk, which I manually encoded. Did this edit make it a literal?

If there are other editorial things you keep doing, perhaps adding some notes to the YouTube import section, or other docs, to try and get these things corrected before PRs get submitted?

**Comment by Daniel-at-github** [comment]
Thanks to you, @glasnt, for the contribution!

It's true that we have to review the documentation. I have recently added more tools:
* My variant of the YouTube import (https://github.com/Daniel-at-github/pyvideo_scrape)
* A tool to review imports and PR (https://github.com/Daniel-at-github/pyvideo_lektor)

Maybe is the summer, but the project is short in person * hours. (Maybe we need a recruiter).

Reserialize and normalizing spaces is an automatic cosmetic thing, I have done it to know what is manually changed with `pyvideo_lektor` (the tool to review).
Fixing the description footer is a global find & replace of data. Copyright have its own field and conference data is related to the talk but it's not the description of it.
I will review it now (if "real life" don't gets in the way) .

**Comment by Daniel-at-github** [comment]
@redapple can you deploy it? (Is the deployment process documented somewhere?)

**Comment by redapple** [comment]
@Daniel-at-github done.
I'm not sure the deployment process is documented,
but what I usually do:

1. start from a clean master of `pyvideo/pyvideo`
```
.../src/pyvideo(master)$ git pull
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 20 (delta 9), reused 14 (delta 9), pack-reused 6
Dépaquetage des objets: 100% (20/20), fait.
Depuis github.com:pyvideo/pyvideo
   ad1799e..d3afbfc  master     -> origin/master
Mise à jour ad1799e..d3afbfc
Fast-forward
 content/pages/thank-you-contributors.rst | 68 ++++----------------------------
 data                                     |  2 +-
 pelicanconf.py                           |  1 +
 themes/pytube-201601/templates/base.html |  2 +-
 tools/used_links.txt                     |  9 +++++
 5 files changed, 20 insertions(+), 62 deletions(-)
```

2. Update sub-project `data/`
```
.../src/pyvideo(master)$ cd data/
.../src/pyvideo/data((HEAD détachée depuis d214cecc))$ git pull origin master
remote: Counting objects: 503, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 503 (delta 462), reused 429 (delta 398), pack-reused 9
Réception d'objets: 100% (503/503), 89.29 KiB | 361.00 KiB/s, fait.
Résolution des deltas: 100% (462/462), complété avec 7 objets locaux.
Depuis https://github.com/pyvideo/data
 * branch              master     -> FETCH_HEAD
   5145bfe5..f5b674ca  master     -> origin/master
Mise à jour 5145bfe5..f5b674ca
Fast-forward
 kiwi-pycon-2017/videos/12704.json                  |  8 ++++--
 pycon-au-2017/videos/lightning-talks-sunday.json   |  2 +-
 pycon-au-2018/category.json                        |  4 +++
[...]
 create mode 100644 pycon-au-2018/videos/you-have-control-learning-lessons-from-aviation.json
```

3. Check that  the local diff is only about the subproject,
and that the commit ID is the latest from `pyvideo/data`

```
.../src/pyvideo(master)$ git diff
diff --git a/data b/data
index 5145bfe..f5b674c 160000
--- a/data
+++ b/data
@@ -1 +1 @@
-Subproject commit 5145bfe5f706f94838def45ff3d5db59e75ac962
+Subproject commit f5b674ca64a0bdf6dbaa38e63e77bffe14dcc82e
```

4. Create PR using `ff-data` branch
```
.../src/pyvideo(master)$ git checkout ff-data 
M	data
Basculement sur la branche 'ff-data'
Votre branche est à jour avec 'origin/ff-data'.

.../src/pyvideo(ff-data)$ git add data/
.../src/pyvideo(ff-data)$ git commit -m "Fast-forward data (2018-09-03)"
[ff-data 587c902] Fast-forward data (2018-09-03)
 1 file changed, 1 insertion(+), 1 deletion(-)

.../src/pyvideo(ff-data)$ git push origin ff-data
Décompte des objets: 2, fait.
Delta compression using up to 8 threads.
Compression des objets: 100% (2/2), fait.
Écriture des objets: 100% (2/2), 267 bytes | 267.00 KiB/s, fait.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:pyvideo/pyvideo.git
   f77742d..587c902  ff-data -> ff-data
```

And merge that PR if green

**Pull request merged**
