### PR TITLE
Pyconfr 2019: add peertube links

### PR DESCRIPTION
**Pull request by pilou-**
PyConFR 2019: add peertube links

Based on #998 in order to preventively fix the conflict.

Notify @JulienPalard.

### CODE REVIEW

**Comment by JulienPalard** [comment]
Wow.

**Comment by pilou-** [comment]
Updated: remove extraneous comma

**Comment by redapple** [comment]
Thanks @pilou- 
I'm not familiar with PeerTube.

For YouTube and Vimeo, PyVideo.org embeds the videos in an `<iframe>` (see https://github.com/pyvideo/pyvideo/blob/190542b9863e06a91def2c54d81e24e09e087f20/plugins/json_reader.py#L142)

My questions to you:
- do all PeerTube videos follow `https://<instance.name>/videos/watch/<uuid>`?
- could we use a unique "peertube" type and transform these using `https://<instance.name>/videos/embed/f04c14bf-8ac1-4b1e-bfc0-14caa80a1674` to be used in an `iframe`?
if yes, I'd rather we adapt the pelican plugin to transform PeerTube URLs to embeddable ones before merging these new URLs.

**Comment by pilou-** [comment]
> My questions to you:
> 
>     * do all PeerTube videos follow `https://<instance.name>/videos/watch/<uuid>`?

Yes, here are some examples:
* https://video.lewd.host/videos/watch/4de251dd-f919-41c3-81a5-d5767904f6c7
* https://video.aprendiz-isi.tk/videos/watch/4de251dd-f919-41c3-81a5-d5767904f6c7
* https://peertube.kangoulya.org/videos/watch/4de251dd-f919-41c3-81a5-d5767904f6c7
* https://peertube.ventresmous.fr/videos/watch/4de251dd-f919-41c3-81a5-d5767904f6c7
* https://video.wivodaim.net/videos/watch/4de251dd-f919-41c3-81a5-d5767904f6c7


Should I added these URLs too ?

>     * could we use a unique "peertube" type and transform these using `https://<instance.name>/videos/embed/f04c14bf-8ac1-4b1e-bfc0-14caa80a1674` to be used in an `iframe`?

Yes, using `videos/embed/<id>`, for example: `https://bittube.video/videos/embed/4de251dd-f919-41c3-81a5-d5767904f6c7`.

>       if yes, I'd rather we adapt the pelican plugin to transform PeerTube URLs to embeddable ones before merging these new URLs.
A proposal: https://github.com/pyvideo/pyvideo/pull/269

**Comment by logston** [comment]
Wow! Sorry for the long delay on this!

**Pull request merged**
