### PR TITLE
Update pycon-2011--ten-years-of-twisted.json

### PR DESCRIPTION
**Pull request by glyph**
Set the "speakers" field correctly so this shows up on my list of talks.

### CODE REVIEW

**Comment by jonemo** [comment]
Thank you for fixing this @glyph!

**Comment by redapple** [comment]
Hi @glyph , we still have to publish the changes from https://github.com/pyvideo/pyvideo; Will do it today

**Comment by redapple** [comment]
@glyph , done.

**Comment by jonemo** [comment]
@glyph: I too was confused about this when I first contributed here. 

Merging to master on the `pyvideo/data` repo doesn't do anything to the site. The site gets updated only when master on the `pyvideo/pyvideo` repo changes (afaik all the static pages get re-generated at that point). 

The way to make the latest contents of `pyvideo/data` to go live is to bump the reference as @redapple did in https://github.com/pyvideo/pyvideo/pull/151

@redapple: Is this actually documented somewhere? Would it make sense to add this information from this comment to `CONTRIBUTING.rst`?

**Pull request merged**
