### PR TITLE
Add category for Python developers in Vancouver.

### PR DESCRIPTION
**Pull request by donkirkby**

### CODE REVIEW

**Comment by Daniel-at-github** [comment]
Do you know if the 6:45 main video will be processed in the future and split into one-talk videos?

**Comment by donkirkby** [comment]
I don't think so. Would it be helpful if I added separate URL's for each talk that would start at the right time?

Thanks for the merge.

**Comment by donkirkby** [comment]
It looks like something is wrong. I see the two videos on the search page for [Vancouver], but I get a 404 from [my video], [VanPyDay], and the [category]. Should I open a separate issue?

[Vancouver]: http://pyvideo.org/search.html?q=vancouver4
[VanPyDay]: http://pyvideo.org/vanpy/vancouver-python-day-2016.html
[my video]: http://pyvideo.org/vanpy/live-coding-in-python-v2-16.html
[category]: http://pyvideo.org/events/vanpy.html

**Comment by Daniel-at-github** [comment]
It's a search bug. Open the issue in https://github.com/pyvideo/pyvideo/issues and reference your https://github.com/pyvideo/data/pull/332#issuecomment-322661939
After the merge the files have to be deployed (usually by @lgh2 or @logston) to pyvideo and the event will appear in http://pyvideo.org/events.html. In this case it have to be done yet.
The search seems to be using the repository files, just now it don't correspond with the deployed files and then we have a 404.

**Comment by Daniel-at-github** [comment]
Substitute the 6:45 main video with one-talk files pointing to the right time seems a good idea to me. For example: 
* "Protect your users with circuit breakers" https://www.youtube.com/watch?v=x6b7U9GpfQk&t=1h8m5s
* ...

All files will point to the same video (and thumbnail), but it will enhance the user experience (Have the metadata and the start time for all videos). And in the improbable case that Python Vancouver process the videos and split it into one-talk videos, all we have to do is replace the url video and thumbnail.

**Pull request merged**
