### PR TITLE
PyTexas 2017

### PR DESCRIPTION
**Pull request by di**

### CODE REVIEW

**Comment by jtemporal** [comment]
Hi @di thank you for your contribution!

**Comment by di** [comment]
Weirdly the videos [show up in searches](http://pyvideo.org/search.html?q=ingram) but [the event links are 404](http://pyvideo.org/events/pytexas-2017.html).

**Comment by lgh2** [comment]
The videos probably aren't appearing because we need to do a fast-forward merge on the main repo.  They happen pretty frequently, if someone hasn't done it by this evening I can take care of it. 

I'm not sure why the event links would be 404. The first thing I'd look at is the json for each video and see if something is off there.  Also, sometimes the events upload their videos to youtube in such a way that we have issues linking to them, it may be worthwhile to look into that if the links are correct.

**Comment by redapple** [comment]
Hi @di , Thank you for your contribution.
I've updated pyvideo.org. (https://github.com/pyvideo/pyvideo/pull/141). [It's live](http://pyvideo.org/events/pytexas-2017.html).

About search, I'm not sure how the website and the search api data are synchronized.
FTR, I started looking at using [@algolia for open source projects](https://www.algolia.com/for-open-source) to keep the two in sync when https://github.com/pyvideo/pyvideo gets updated.

**Comment by di** [comment]
Great, thanks @lgh2 and @redapple!

**Pull request merged**
