### PR TITLE
Pycon finland 2015 and 2016

### PR DESCRIPTION
**Pull request by Daniel-at-github**
Closes issue #126

### CODE REVIEW

**Comment by redapple** [comment]
It looks like all (recorded) PyCon Finland 2015 talks happened on 2015-10-19, not 2015-11-03 (http://fi.pycon.org/2015/#schedule)

**Comment by redapple** [comment]
And PyCon Finland 2016 talks were on 2016-10-31 (http://fi.pycon.org/2016/#schedule)

**Comment by Daniel-at-github** [comment]
Thanks for the review.
Usually dates are approximate, given the work involved on getting it right.

**Comment by redapple** [comment]
True @Daniel-at-github . I just happened to have had a look at PyCon Finland around the same time.
I started to pay attention to dates after noticing not-most-recent talks under "Latest" on the homepage.

**Pull request merged**
