### PR TITLE
Our videos got deleted from a youtube account we don't own. I uploaded them back.

### PR DESCRIPTION
**Pull request by JulienPalard**
All in the title.

Looks like those video were uploaded by the company that recorded them for us, and the company closed their youtube channel.

I had a backup so I uploaded them back on youtube plus our own server and enhanced the metadata a bit. Upload to peertube soon™.

### CODE REVIEW

**Comment by JulienPalard** [comment]
It's been ~two days and it seems not yet in production: https://pyvideo.org/pycon-fr-2016/faut-il-etre-masochiste-pour-utiliser-ipv6-dans-son-code-python.html

Is it normal or is it an issue?

**Comment by logston** [comment]
Oh! I'll need to issue a PR against they pyvideo/pyvideo repo to update the data commit. I'll do that now.

**Comment by logston** [comment]
https://github.com/pyvideo/pyvideo/pull/290

**Comment by JulienPalard** [comment]
TIL. Thanks!!

**Pull request merged**
