### PR TITLE
Import djangocon-us-2017

### PR DESCRIPTION
**Pull request by glasnt**
Fixes https://github.com/pyvideo/data/issues/358
Mass import from youtube, manual speaker name pulled from Youtube title, static date.

### CODE REVIEW

**Comment by glasnt** [comment]
@redapple Done!

**Comment by redapple** [comment]
wow that was quick!

**Comment by redapple** [comment]
@glasnt , I did a few changes in https://github.com/glasnt/data/pull/1

**Comment by glasnt** [comment]
@redapple changes merged

**Comment by glasnt** [comment]
Hi @redapple did I need to change anything else before this can be merged?

**Comment by redapple** [comment]
hi @glasnt , at some point, I wanted to get the dates correct instead of the static value, but it's probably fine as it is :)
Oh, and now I see I missed to fix "Butter smooth, interactive applications with Django and Websockets"

**Comment by glasnt** [comment]
@redapple merged!

**Comment by glasnt** [comment]
Thank you for your help, @redapple. I'll know what to get right first time for next time!

**Comment by redapple** [comment]
Thank you @glasnt !

**Pull request merged**
